name = "Trysil"
license = "Apache-2.0"
licenselink = "https://github.com/danielroelfs/hugo-theme-trysil/blob/main/LICENSE"
description = "A simple Hugo theme focused on readability"
homepage = "https://github.com/danielroelfs/hugo-theme-trysil"
tags = ["clean", "simple", "minimalist", "trysil", ]
features = ["readability", "simple"]
min_version = "0.120.0"

[author]
  name = "Daniel Roelfs"
  homepage = "https://danielroelfs.com"